import type { Metadata } from "next";
import { pretendard } from "../shared/config/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} app-shell antialiased`}>
        <div className="app-frame">{children}</div>
      </body>
    </html>
  );
}
